export const ADD_DATA_CART = "UPDATE_DATA_CART";
export const UPDATE_DATA_CART = "UPDATE_DATA_CART";
export const REMOVE_ALL_DATA = "REMOVE_ALL_DATA";
export const REMOVE_DATA = "REMOVE_DATA";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
